import { LegalPage } from "../../components/LegalPage";

export const metadata = { title: "Privacy Policy — Vouch" };

export default function PrivacyPolicyPage() {
  return (
    <LegalPage title="Privacy Policy" updatedDate="July 7, 2026">
      <p className="text-sm bg-yellow-50 border border-yellow-200 rounded-lg px-4 py-3 text-yellow-800">
        This page is a placeholder template and has not been reviewed by
        legal counsel. Replace it with a policy reviewed by a lawyer before
        launching publicly.
      </p>

      <h2>1. Introduction</h2>
      <p>
        This Privacy Policy explains how Vouch (&ldquo;we&rdquo;,
        &ldquo;us&rdquo;, or &ldquo;our&rdquo;) collects, uses, and shares
        information when you use our mobile application and web dashboard
        (together, the &ldquo;Service&rdquo;).
      </p>

      <h2>2. Information We Collect</h2>
      <p>We collect the following categories of information:</p>
      <ul>
        <li>
          <strong>Account &amp; profile data:</strong> name, nickname, email
          address, phone number, birth date, address, city, zip code,
          country, bio, and profile photo.
        </li>
        <li>
          <strong>Referral/sponsor data:</strong> the sponsor who referred
          you and your position in the referral network.
        </li>
        <li>
          <strong>Social links:</strong> any social media handles you choose
          to add to your profile (Facebook, Instagram, Twitter, TikTok,
          Discord, WeChat, Line).
        </li>
        <li>
          <strong>Content you create:</strong> posts, events, library items,
          comments, likes, endorsements, and any images or documents you
          upload.
        </li>
        <li>
          <strong>Device data:</strong> a push-notification device token
          used to deliver notifications to your device.
        </li>
        <li>
          <strong>Support communications:</strong> messages you send us
          through the Contact Us form, including account-deletion requests.
        </li>
        <li>
          <strong>Diagnostic data:</strong> error logs generated by the app
          to help us fix bugs and improve stability.
        </li>
      </ul>

      <h2>3. How We Use Information</h2>
      <ul>
        <li>To create and manage your account and referral network.</li>
        <li>To operate core features: posts, events, library, groups, and notifications.</li>
        <li>To send push notifications about content relevant to you.</li>
        <li>To respond to support requests and account-deletion requests.</li>
        <li>To maintain the security and stability of the Service.</li>
      </ul>

      <h2>4. How We Share Information</h2>
      <p>
        Profile information you mark as visible (nickname, photo, bio, and
        social links) is visible to other members of your network within the
        Service. We do not sell your personal data. We may share data with
        service providers who help us operate the Service (e.g. hosting,
        email delivery, push notifications), each bound by confidentiality
        obligations.
      </p>

      <h2>5. Data Retention</h2>
      <p>
        We retain your data for as long as your account is active. If you
        request account deletion via the Contact Us form or in-app request,
        we mark your account for deletion and remove or anonymize personal
        data within a reasonable period, except where retention is required
        by law.
      </p>

      <h2>6. Your Choices</h2>
      <ul>
        <li>You can edit or remove most profile fields at any time.</li>
        <li>You can request account deletion from within the app or by contacting us.</li>
        <li>You can disable push notifications from your device settings.</li>
      </ul>

      <h2>7. Security</h2>
      <p>
        We use reasonable administrative, technical, and physical safeguards
        to protect your information. No method of transmission or storage is
        100% secure, and we cannot guarantee absolute security.
      </p>

      <h2>8. Children&rsquo;s Privacy</h2>
      <p>
        The Service is not directed to children under 13, and we do not
        knowingly collect personal information from children under 13.
      </p>

      <h2>9. Changes to This Policy</h2>
      <p>
        We may update this Privacy Policy from time to time. We will update
        the &ldquo;Last updated&rdquo; date above when we do.
      </p>

      <h2>10. Contact Us</h2>
      <p>
        If you have questions about this Privacy Policy or how we handle
        your data, contact us through the Contact Us form in the app.
      </p>
    </LegalPage>
  );
}
