export const EVENT_TYPES: string[] = [
  "Health Club",
  "Webinar",
  "Networking",
  "Training",
  "Social",
  "Product Launch",
  "Other",
  "Workshop (WS)",
  "Business Opportunity Meetup (BOM)",
  "Business Builder Training (BBT)",
  "Product Opportunity Meetup (POM)",
  "Product Session (PS)",
  "Case Sharing (CS)",
  "Professional Training (PT)",
  "Gathering",
  "Leaders' Training",
  "Conference",
  "Nu Skin Expo (EXPO)",
  "Meet-up",
  "Incentive Trips",
];
