// Static list of geographic/business markets a member can choose to "follow"
// on their profile. No shared market enum exists elsewhere in the app yet;
// this leads with the China / non-China split already used for video links
// elsewhere in the app (chinaVideoLink / nonChinaVideoLink).
// "ALL" is a sentinel meaning "follow every market" — it's the default and
// is mutually exclusive with picking specific markets.
export const ALL_MARKETS = "ALL";

export const MARKETS: string[] = [
  "Greater China",
  "North America",
  "Latin America",
  "Europe",
  "Southeast Asia",
  "South Asia",
  "Middle East",
  "Africa",
  "Oceania",
  "United States",
  "Canada",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bangladesh",
  "Belarus",
  "Belgium",
  "Belize",
  "Bermuda",
  "Bolivia",
  "Bosnia and Herzegowina",
  "Brazil",
  "Bulgaria",
  "Cayman Islands",
  "Chile",
  "China",
  "Colombia",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "Finland",
  "France",
  "Georgia",
  "Germany",
  "Gibraltar",
  "Greece",
  "Guatemala",
  "Hong Kong",
  "Hungary",
  "India",
  "Indonesia",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Korea, Democratic People's Republic of",
  "Kuwait",
  "Malaysia",
  "Mexico",
  "Netherlands",
  "New Zealand",
  "Norway",
  "Pakistan",
  "Palestine",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Romania",
  "Russian Federation",
  "Saudi Arabia",
  "Singapore",
  "Slovakia (Slovak Republic)",
  "Slovenia",
  "South Africa",
  "Spain",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Thailand",
  "Turkey",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States minor outlying islands",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Serbia",
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Bahrain",
  "Barbados",
  "Benin",
  "Bhutan",
  "Botswana",
  "Bouvet Island",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Cape Verde",
  "Central African Republic",
  "Chad",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Comoros",
  "Congo",
  "Congo (Democratic Republic of the)",
  "Cook Islands",
  "Cote D'Ivoire",
  "Djibouti",
  "Dominica",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fiji",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Ghana",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guinea",
  "Guinea-bissau",
  "Guyana",
  "Haiti",
  "Heard and Mc Donald Islands",
  "Honduras",
  "Iceland",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Kenya",
  "Kiribati",
  "Korea",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libyan Arab Jamahiriya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands Antilles",
  "New Caledonia",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Oman",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Pitcairn",
  "Reunion",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Senegal",
  "Seychelles",
  "Sierra Leone",
  "Solomon Islands",
  "Somalia",
  "South Georgia & South Sandwich Islands",
  "South Sudan",
  "Sri Lanka",
  "St. Helena",
  "St. Pierre and Miquelon",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen Islands",
  "Swaziland",
  "Syrian Arab Republic",
  "Tajikistan",
  "Tanzania",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Vanuatu",
  "Vatican City State (Holy See)",
  "Viet Nam",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna Islands",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
